"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/Badge";

interface DailyBriefing {
  headline: string;
  topPlays: { label: string; sport: string; supportCount: number; angle: string }[];
  fadeAngles: { label: string; reasoning: string }[];
  hotAccounts: string[];
  coldAccounts: string[];
  marketNotes: string;
  generatedAt: string;
}

export default function BriefingPage() {
  const [briefing, setBriefing] = useState<DailyBriefing | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/briefing")
      .then((r) => r.json())
      .then((d) => setBriefing(d.briefing))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="p-4 pb-24">
        <p className="text-zinc-400 text-sm">Loading briefing...</p>
      </div>
    );
  }

  if (!briefing) {
    return (
      <div className="p-4 pb-24">
        <h1 className="text-xl font-bold mb-2">Morning Briefing</h1>
        <div className="bg-zinc-900 rounded-xl p-4 border border-zinc-800">
          <p className="text-zinc-400 text-sm">
            No briefing yet today. The worker generates one each morning after scanning accounts.
          </p>
          <p className="text-zinc-600 text-xs mt-2">
            Run <code className="bg-zinc-800 px-1 rounded">pnpm worker:once</code> to generate now.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 pb-24 space-y-4">
      <div>
        <h1 className="text-xl font-bold">Morning Briefing</h1>
        <p className="text-xs text-zinc-500 mt-0.5">
          {new Date(briefing.generatedAt).toLocaleString()} · Generated by Claude Sonnet
        </p>
      </div>

      {/* Headline */}
      <div className="bg-blue-950 border border-blue-800 rounded-xl p-4">
        <p className="text-blue-200 font-semibold leading-snug">{briefing.headline}</p>
      </div>

      {/* Top plays */}
      {briefing.topPlays.length > 0 && (
        <section>
          <h2 className="text-sm font-semibold text-zinc-400 mb-2">Top Consensus Plays</h2>
          <div className="space-y-2">
            {briefing.topPlays.map((play, i) => (
              <div key={i} className="bg-zinc-900 rounded-xl p-4 border border-zinc-800">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-semibold text-white">{play.label}</span>
                  <Badge label={play.sport} color="green" />
                  <Badge label={`${play.supportCount} accounts`} color="zinc" />
                </div>
                <p className="text-sm text-zinc-300">{play.angle}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Fade angles */}
      {briefing.fadeAngles.length > 0 && (
        <section>
          <h2 className="text-sm font-semibold text-zinc-400 mb-2">Fade Angles</h2>
          <div className="space-y-2">
            {briefing.fadeAngles.map((fade, i) => (
              <div key={i} className="bg-zinc-900 rounded-xl p-4 border border-red-900">
                <p className="font-semibold text-red-300 mb-1">{fade.label}</p>
                <p className="text-sm text-zinc-300">{fade.reasoning}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Market notes */}
      <section>
        <h2 className="text-sm font-semibold text-zinc-400 mb-2">Market Notes</h2>
        <div className="bg-zinc-900 rounded-xl p-4 border border-zinc-800">
          <p className="text-sm text-zinc-200 leading-relaxed">{briefing.marketNotes}</p>
        </div>
      </section>

      {/* Account activity */}
      {(briefing.hotAccounts.length > 0 || briefing.coldAccounts.length > 0) && (
        <section>
          <h2 className="text-sm font-semibold text-zinc-400 mb-2">Account Activity</h2>
          <div className="bg-zinc-900 rounded-xl p-4 border border-zinc-800 space-y-2">
            {briefing.hotAccounts.length > 0 && (
              <div>
                <span className="text-xs text-green-400 font-medium">Active today: </span>
                <span className="text-sm text-zinc-300">
                  {briefing.hotAccounts.map((u) => `@${u}`).join(", ")}
                </span>
              </div>
            )}
            {briefing.coldAccounts.length > 0 && (
              <div>
                <span className="text-xs text-zinc-500 font-medium">Quiet: </span>
                <span className="text-sm text-zinc-500">
                  {briefing.coldAccounts.map((u) => `@${u}`).join(", ")}
                </span>
              </div>
            )}
          </div>
        </section>
      )}
    </div>
  );
}
